// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCloudFiles;

namespace SimpleCloudFiles.Migrations
{
    [DbContext(typeof(CfDbContext))]
    [Migration("20210914153450_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("SimpleCloudFiles.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = "4548c99fa90b41e19283b046fff14ec9",
                            CreateTime = new DateTime(2021, 9, 14, 23, 34, 49, 892, DateTimeKind.Local).AddTicks(7935),
                            Password = "E10ADC3949BA59ABBE56E057F20F883E",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("SimpleCloudFiles.Models.CfFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ext")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Md5")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceMd5")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CfFiles");
                });

            modelBuilder.Entity("SimpleCloudFiles.Models.Dir", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dirs");

                    b.HasData(
                        new
                        {
                            Id = "4329f1a476204af68493bba52d022728",
                            AccountId = "4548c99fa90b41e19283b046fff14ec9",
                            CreateTime = new DateTime(2021, 9, 14, 23, 34, 49, 895, DateTimeKind.Local).AddTicks(2221),
                            DirId = "",
                            Name = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
